server:
  port: 8070

spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/mylib?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    password: 123456
    timeout: 1800000
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

